artifacts_dir : artifacts

data_ingestion :
  root_dir : artifacts/data_ingestion
  source_dir : data/raw/Crop_recommendation.csv
  train_dir : artifacts/data_ingestion/train.csv
  test_dir : artifacts/data_ingestion/test.csv
  test_size : 0.2
  random_state : 42
