stages:
  data_ingestion:
    cmd: PYTHONPATH=src python src/crop_recommendation/pipelines/pipeline_01_data_ingestion.py

    deps:
      - config/config.yaml
      - data/raw/Crop_recommendation.csv
      - src/crop_recommendation/components/data_ingestion.py
      - src/crop_recommendation/config/config.py
      - src/crop_recommendation/entity/entity.py

    outs:
      - artifacts/data_ingestion/raw.csv
      - artifacts/data_ingestion/train.csv
      - artifacts/data_ingestion/test.csv


  data_validation:
    cmd: PYTHONPATH=src python src/crop_recommendation/pipelines/pipeline_02_data_validation.py
    deps:
      - artifacts/data_ingestion/train.csv
      - config/config.yaml
      - config/schema.yaml
      - src/crop_recommendation/components/data_validation.py
      - src/crop_recommendation/config/config.py
      - src/crop_recommendation/entity/entity.py
    outs:
      - artifacts/data_validation/status.txt

  data_preprocessing:
    cmd: PYTHONPATH=src python src/crop_recommendation/pipelines/pipeline-03-data_preprocessing.py

    deps:
      - src/crop_recommendation/components/data_preprocessing.py
      - src/crop_recommendation/config/config.py
      - src/crop_recommendation/entity/entity.py
      - artifacts/data_ingestion/train.csv
      - artifacts/data_ingestion/test.csv

    outs:
      - artifacts/data_preprocessing/train.npy
      - artifacts/data_preprocessing/test.npy
      - artifacts/data_preprocessing/preprocessor.pkl
      - artifacts/data_preprocessing/label_encoder.pkl
